Orders/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='Orders'
urlpatterns = [
    path('', views.process_order, name='process_order'),

]

ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

cart/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='cart'
urlpatterns = [
    path('add/<int:product_id>', views.add_product, name='add_product'),
    path('delete/<int:product_id>', views.delete_product, name='delete_product'),
    path('subtract/<int:product_id>', views.subtract_product, name='subtract_product'),
    path('clearcart/', views.clear_cart, name='clear_cart'),
]

store/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='store'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='all'),
    path('product/<int:pk>', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/create',
        views.ProductCreateView.as_view(success_url=reverse_lazy('store:all')), name='product_create'),
    path('product/<int:pk>/update',
        views.ProductUpdateView.as_view(success_url=reverse_lazy('store:all')), name='product_update'),
    path('product/<int:pk>/delete',
        views.ProductDeleteView.as_view(success_url=reverse_lazy('store:all')), name='product_delete'),
    path('product_picture/<int:pk>', views.stream_file, name='product_picture'),
    path('product/<int:pk>/comment',
        views.Product_CommentCreateView.as_view(), name='product_comment_create'),
    path('comment/<int:pk>/delete',
        views.Product_CommentDeleteView.as_view(success_url=reverse_lazy('store:all')), name='product_comment_delete'),
    path('product/<int:pk>/favorite',
        views.AddProduct_FavoriteView.as_view(), name='product_favorite'),
    path('product/<int:pk>/unfavorite',
        views.DeleteProduct_FavoriteView.as_view(), name='product_unfavorite'),
]

store/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class Product(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    tags = TaggableManager(blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Product_Comment', related_name='product_comments_owned')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Product_Fav', related_name='favorite_products')
    category = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Product_Category', related_name='category_products')
    available = models.BooleanField(default=True)
    # Shows up in the admin list
    def __str__(self):
        return self.title

class Product_Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'

class Product_Fav(models.Model) :
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/4.2/ref/models/options/#unique-together
    class Meta:
        unique_together = ('product', 'user')

    def __str__(self) :
        return '%s likes %s'%(self.user.username, self.product.title[:10])


class Product_Category(models.Model):
    title = models.CharField(
            max_length=50,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self) :
        return self.title

store/forms.py
from django import forms
from store.models import Product
from django.core.files.uploadedfile import InMemoryUploadedFile
from ads.humanize import naturalsize


# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Product
        fields = ['title', "price", "tags", 'text', 'picture']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
            self.save_m2m()

        return instance

class Product_CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

# https://docs.djangoproject.com/en/4.2/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/4.2/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

cart/views.py
from django.shortcuts import render, redirect
from .carro import Cart
from store.models import Product

# Create your views here.

def add_product(request, product_id):
    
    cart= Cart(request)
    product=Product.objects.get(id=product_id)
    cart.add(product=product)

    return redirect(request.META.get('HTTP_REFERER'))

def delete_product(request, product_id):
    
    cart= Cart(request)
    product=Product.objects.get(id=product_id)
    cart.delete(product=product)

    return redirect(request.META.get('HTTP_REFERER'))

def subtract_product(request, product_id):
    
    cart= Cart(request)
    product=Product.objects.get(id=product_id)
    cart.subtract(product=product)

    return redirect(request.META.get('HTTP_REFERER'))

def clear_cart(request):
    
    cart= Cart(request)
    cart.clear_cart()

    return redirect(request.META.get('HTTP_REFERER'))

store/views.py
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q
from django.core.paginator import Paginator

from store.models import Product, Product_Comment, Product_Fav
from store.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView
from store.forms import CreateForm, Product_CommentForm


class ProductListView(OwnerListView):
    model = Product
    template_name = "store/product_list.html"
    # template_name = "myarts/article_list.html"

    def get(self, request) :
        strval =  request.GET.get("search", False)
        if strval :
            # Simple title-only search
            # objects = Post.objects.filter(title__contains=strval).select_related().distinct().order_by('-updated_at')[:10]

            # Multi-field search
            # __icontains for case-insensitive search
            query = Q(title__icontains=strval)
            query.add(Q(text__icontains=strval), Q.OR)
            query.add(Q(tags__name__in=[strval]), Q.OR)
            product_list = Product.objects.filter(query).select_related().distinct().order_by('-updated_at')[:10]
            paginator = Paginator(product_list, 4)  # Show 4 contacts per page.
            page_number = request.GET.get("page")
            page_obj = paginator.get_page(page_number)
        else :
            product_list = Product.objects.all().order_by('-updated_at')[:10]
            paginator = Paginator(product_list, 4)  # Show 4 contacts per page.
            page_number = request.GET.get("page")
            page_obj = paginator.get_page(page_number)
        for obj in page_obj:
            obj.natural_updated = naturaltime(obj.updated_at)
        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_products.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [ row['id'] for row in rows ]
        ctx = {'product_list' : product_list, 'favorites': favorites, 'search': strval, "page_obj":page_obj}
        return render(request, self.template_name, ctx)

    # By convention:



class ProductDetailView(OwnerDetailView):
    model = Product
    template_name = "store/product_detail.html"
    def get(self, request, pk) :
        x = get_object_or_404(Product, id=pk)
        comments = Product_Comment.objects.filter(product=x).order_by('-updated_at')
        comment_form = Product_CommentForm()
        context = { 'product' : x, 'comments': comments, 'comment_form': comment_form }
        return render(request, self.template_name, context)

class ProductCreateView(OwnerCreateView, View):
    template_name = 'store/product_form.html'
    success_url = reverse_lazy('store:all')
    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Adjust the model owner before saving
        inst = form.save(commit=False)
        inst.owner = self.request.user
        inst.save()

        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
        form.save_m2m()    # Add this
        return redirect(self.success_url)
        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false



class ProductUpdateView(LoginRequiredMixin, View):
    template_name = 'store/product_form.html'
    success_url = reverse_lazy('store:all')

    def get(self, request, pk):
        pic = get_object_or_404(Product, id=pk, owner=self.request.user)
        form = CreateForm(instance=pic)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        pic = get_object_or_404(Product, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=pic)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        pic = form.save(commit=False)
        pic.save()
        form.save_m2m()

        return redirect(self.success_url)


class ProductDeleteView(OwnerDeleteView):
    model = Product

def stream_file(request, pk):
    product = get_object_or_404(Product, id=pk)
    response = HttpResponse()
    response['Content-Type'] = product.content_type
    response['Content-Length'] = len(product.picture)
    response.write(product.picture)
    return response

class Product_CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        a = get_object_or_404(Product, id=pk)
        comment = Product_Comment(text=request.POST['comment'], owner=request.user, product=a)
        comment.save()
        return redirect(reverse('store:product_detail', args=[pk]))

class Product_CommentDeleteView(OwnerDeleteView):
    model = Product_Comment
    template_name = "store/comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        product = self.object.product
        return reverse('store:product_detail', args=[product.id])

@method_decorator(csrf_exempt, name='dispatch')
class AddProduct_FavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Add PK",pk)
        product = get_object_or_404(Product, id=pk)
        fav = Product_Fav(user=request.user, product=product)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError:
            pass
        return HttpResponse()

@method_decorator(csrf_exempt, name='dispatch')
class DeleteProduct_FavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Delete PK",pk)
        product = get_object_or_404(Product, id=pk)
        try:
            fav = Product_Fav.objects.get(user=request.user, product=product).delete()
        except Product_Fav.DoesNotExist:
            pass

        return HttpResponse()

store/templates/store/cart.html
<table class="table table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">Product</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
        </tr>
    </thead>

    <tbody>
        {% if request.session.cart.items %}
            {% for key, value in request.session.cart.items %}
                <tr>
                    <td>{{value.title}}</td>
                    <td>
                        <a href="{% url "cart:subtract_product" value.product_id %}"class="btn btn-sm btn-success">-</a>
                        {{value.quantity}}
                        <a href="{% url "cart:add_product" value.product_id %}"class="btn btn-sm btn-success">+</a>
                    </td>
                    <td>{{value.price}}</td>
                </tr>

            {% endfor %}
                <tr>
                    <td colspan="2">Total: ${{total_cart}}</td>
                    {% if user.is_authenticated %}
                    <td colspan="" class="justify-content-center">
                        <a href="{% url "Orders:process_order"%}"class="btn btn-sm btn-success">Buy</a>
                    </td>
                    {% endif %}
                </tr>                 
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Empty Cart
                    </div>
                </td>
            </tr>

        {% endif %}
    </tbody>





</table>

store/templates/store/comment_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ product_comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'store:product_detail' product_comment.product.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

store/templates/store/product_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Ad</h1>

<p>Are you sure you want to delete the product: {{ product }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

store/templates/store/product_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/4.2/ref/contrib/humanize -->
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% block content %}
{% if product.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'store:product_picture' product.id %}">
</div>
{% endif %}
<span style="float: right;">
({{ product.updated_at|naturaltime }})
{% if product.owner == user %}
<a href="{% url 'store:product_update' product.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'store:product_delete' product.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ product.title }}</h1>
{% if product.content_type %}
<img style="float:right; max-width:50%;" src="{% url 'store:product_picture' product.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}
<p>
{{ product.text }}
</p>
{% if product.tags.all %}
<p>Tags:
  {% for tag in product.tags.all %}
  <span style="border:1px grey solid; background-color: LightGreen;">{{ tag }}</span>
  {% endfor %}
</p>
{% endif %}
<p>
Price: ${{ product.price }}
</p>
<p>
<p>
({{ product.updated_at|naturaltime }})
</p>
{% if user.is_authenticated %}
<br clear="all"/>
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'store:product_comment_create' product.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
<input type="submit" value="All Ads" onclick="window.location.href='{% url 'store:all' %}';return false;">
</form>
</p>
{% endif %}
{% for comment in comments %}
<p> {{ comment.text }}
({{ comment.updated_at|naturaltime }})
{% if user == comment.owner %}
<a href="{% url 'store:product_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
{% endfor %}
</p>
</p>
<p>
<a href="{% url 'store:all' %}">All Products</a>
</p>
{% endblock %}

store/templates/store/product_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'store:all' %}';return false;">
  </form>
</p>
<script>
document.getElementById("upload_form").addEventListener("submit", function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = document.getElementById('id_{{ form.upload_field_name }}').files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

store/templates/store/product_list.html
{% extends "base_menu.html" %}
{% block content %}
<div class="row">
    <h1 class="col-3">Store</h1>
    <div class="col-9" style="text-align: right;">
    <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
        <form>
            <input type="text" placeholder="Search.." name="search"
            {% if search %} value="{{ search }}" {% endif %}
            >
            <button type="submit"><i class="fa fa-search"></i></button>
            <a href="{% url 'store:all' %}"><i class="fa fa-undo"></i></a>
        </form>
    </div>
</div>

<div class="container">
    <div style="float:right;">
        {% include "store/cart.html" %}
    </div>
    <div class="row align-items-start" >
        {% if page_obj %}    
        {% for product in page_obj %}
        <div class="col-9 col-md-3">
                <div class="card" style="width: 100%;margin: 5px 5px;">
                    {% if product.content_type %}
                    <img class="card-img-top" style="width:100%;height:100%;margin-top: 0px; border:0px solid black;" src="{% url 'store:product_picture' product.id %}">
                    {% endif %}
                    <div class="">

                        <div class="card-body">
                            <div class="card-title">
                                <a href="{% url 'store:product_detail'  product.id %}">{{ product.title }}</a>
                                <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
                                <a href="#" onclick=
                                    "favPost('{% url 'store:product_unfavorite' product.id %}', {{ product.id }} );return false;"
                                    {% if product.id not in favorites %} style="display: none;" {% endif %}
                                    id="favorite_star_{{product.id}}">
                                <span class="fa-stack" style="vertical-align: middle;">
                                <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                                <i class="fa fa-star-o fa-stack-1x"></i>
                                </span>
                                </a>
                                <!-- the second href -->
                                <a href="#" onclick=
                                    "favPost('{% url 'store:product_favorite' product.id %}', {{ product.id }} );return false;"
                                    {% if product.id in favorites %} style="display: none;" {% endif %}
                                    id="unfavorite_star_{{product.id}}">
                                <span class="fa-stack" style="vertical-align: middle;">
                                <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
                                <i class="fa fa-star-o fa-stack-1x"></i>
                                </span>
                                </a>
                            <div  class="card-subtitle mb-2 text-muted">
                                    Price: ${{ product.price }} 
                            </div>
                            <div class="card-link">
                                {% if product.owner == user %}
                                (<a href="{% url 'store:product_update' product.id %}">Edit</a> |
                                <a href="{% url 'store:product_delete' product.id %}">Delete</a>)
                                {% endif %}
                            </div>
                            
                                {% if user.is_authenticated %}

                                {% endif %}
                            </div>
                            

                            <!-- 
                            <div class="card-text">
                                {% if product.text|length < 100 %}
                                    Description: {{ product.text }}
                                {% else %}
                                    Description: {{ product.text|slice:"0:30" }}
                                    <a href="{% url 'well:post_detail'  post.id %}">...</a>
                                {% endif %}
                            </div>

                            <small>
                                {% if product.owner.username %}
                                    posted by {{ product.owner.username }}
                                {% endif %}
                                {{ product.natural_updated }}
                            </small> -->

                        </div>
                        <div class="card-footer text-center">
                            <a href="{% url "cart:add_product" product.id %}"class="btn btn-sm btn-success" >Add to the Cart</a>
                        </div> 


                    </div>
                </div>
        </div>
        {% endfor %}
            
        {% else %}
        <p>There are no products in the database.</p>
        
        {% endif %}

        <!--Pagination if search and normal-->
        {% if search %}
        <nav aria-label="...">
            <ul class="pagination justify-content-center" >
                <li class="">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?search={{ search }}&page=1">First</a>
                        </li>
                        <li>
                            <a class="page-link"href="?search={{ search }}&page={{ page_obj.previous_page_number }}">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link">First </a>
                        </li>
                        <li class="page-item disabled">
                            <a class="page-link">Previous</a>
                        </li>
                    {% endif %}
                    {% for page_obj in page_obj.paginator.get_elided_page_range %}
                        <li class="page-item"><a class="page-link" href="?search={{ search }}&page={{ page_obj }}">{{ page_obj }}</a></li>
                    {% endfor%}
                    <!--<li class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </li>-->
            
                    {% if page_obj.has_next %}
                        <a class="page-link" href="?search={{ search }}&page={{ page_obj.next_page_number }}">Next</a>
                        <a class="page-link" href="?search={{ search }}&page={{ page_obj.paginator.num_pages }}">Last </a>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link">Next</a>
                        </li>
                        <li class="page-item disabled">
                            <a class="page-link">Last </a>
                        </li>
                    {% endif %}
        {% else %}
            <nav aria-label="...">
                <ul class="pagination justify-content-center" >
                    <li class="">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1">First</a>
                            </li>
                            <li>
                                <a class="page-link"href="?page={{ page_obj.previous_page_number }}">Previous</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link">First </a>
                            </li>
                            <li class="page-item disabled">
                                <a class="page-link">Previous</a>
                            </li>
                        {% endif %}
                        {% for page_obj in page_obj.paginator.get_elided_page_range %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj }}">{{ page_obj }}</a></li>
                        {% endfor%}
                        <!--<li class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </li>-->
                
                        {% if page_obj.has_next %}
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last </a>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link">Next</a>
                            </li>
                            <li class="page-item disabled">
                                <a class="page-link">Last </a>
                            </li>
                        {% endif %}
                    </li>
                </ul>
            </nav>
        {% endif %}
    </div>
</div>


<!--
<p>
<a href="{% url 'store:product_create' %}">Add an Product</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'store:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'store:all' %}">Login</a>
{% endif %}
</p>-->
<script>
function toggleInlineDisplay(star_id) {
    var elem = document.getElementById(star_id);
    if(window.getComputedStyle(elem).display == "inline") {
        elem.style.display = 'none';
        elem.dataset.previousDisplay = 'inline';
    } else if(window.getComputedStyle(elem).display == "block") {
        elem.style.display = 'none';
        elem.dataset.previousDisplay = 'block';
    } else {
        console.log('prev', elem.dataset.previousDisplay);
        if ( typeof elem.dataset.previousDisplay == 'string' ) {
            elem.style.display = elem.dataset.previousDisplay
        } else {
            elem.style.display = 'inline';
        }
    }
}

function favPost(url, thing_id) {
    console.log('POSTing to', url);
    fetch(url, { method: 'POST', body: '{}' } )
    .then((response) => {
        console.log(url, 'finished');
        toggleInlineDisplay("unfavorite_star_"+thing_id);
        toggleInlineDisplay("favorite_star_"+thing_id);
    }).catch((error) => {
        alert('Url failed with '+error+' '+url);
    });
}
</script>
{% endblock %}